# Generated by Django 3.1.6 on 2021-02-03 19:51

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('key', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('required_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Number', models.IntegerField()),
                ('Question_Text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Question_Answer', models.CharField(max_length=50)),
                ('Question_Round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.round')),
            ],
        ),
    ]
